on: [push]

name: mabl

jobs:
  test:
    name: Mabl Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm ci

      - name: Compile typescript
        run: npm run build

      - name: Install mabl CLI
        uses: ./
        env:
          MABL_API_KEY: ${{ secrets.MABL_API_KEY }}
        with:
          # Try variants
          workspace: vjnf0NH86WlzPTdU5JNhmg-w
          workspace_id: vjnf0NH86WlzPTdU5JNhmg-w
          workspace-id: vjnf0NH86WlzPTdU5JNhmg-w

      - name: List applications
        run: mabl applications list

